### PR TITLE
print list of releases before prompting user to specify version #

### PR DESCRIPTION
**Pull request by not-tacos**
also modified the linux update prompt to act like apt's own prompt

### CODE REVIEW

**Comment by not-tacos** [comment]
superseded by new PR.

**Comment by Alexd1985** [comment]
Thanks man, but I see the pull is closed now?
Why?

**Comment by not-tacos** [comment]
everything in this PR was wiped out by what's in the new one.

**Comment by Alexd1985** [comment]
good job man I love it! well done

**Pull request closed without merging**
