### PR TITLE
minor grammar fixes

### PR DESCRIPTION
**Pull request by not-tacos**

### CODE REVIEW

**Comment by not-tacos** [comment]
I've got a couple ideas for more functional changes, but those are going to take a little time to implement.

**Comment by Alexd1985** [comment]
Thanks man! 🍻

**Comment by Alexd1985** [comment]
I want for the script to make a versions available on git.. for example if someone will enter 1.3.3.0 by mistake.. to receive an error .. version is wrong/not available.. but I am learning

**Comment by Alexd1985** [comment]
And also at the end to ask if u want to start or not the glive.. (I know how to do this)

**Comment by not-tacos** [comment]
> I want for the script to make a versions available on git.. for example if someone will enter 1.3.3.0 by mistake.. to receive an error .. version is wrong/not available.. but I am learning

That's similar to what I was thinking. We could _possibly_ even have it suggest the latest public release and auto-grab that after confirming with the user. If they don't want to install the latest release, _then_ we prompt them for the version to install. Could even list the most recent 10 releases and let the user select from a list.

My other idea was to accept arguments from the command line and run silently, for those who want to deploy it easier.


I've always turned your update tutorials into shell scripts, but mine weren't ever so pretty so I never thought to share them. (also they only worked for one version because I never bothered to make them flexible.)

Maybe this would be a good addition to CNTOOLS? Updating the node would be an excellent (and logical) feature for that project.

**Comment by Alexd1985** [comment]
Yes, I was thinking of that.. to be added to prereqs

will keep in touch 

Cheers,

**Comment by not-tacos** [comment]
> And also at the end to ask if u want to start or not the glive.. (I know how to do this)

The auto-start of gLiveView is my favorite feature!
Maybe we can use tmux to also display a small section of cnode logs in another pane of the terminal window, and the leaderlog printouts in another. I have all 3 of these open in different terminal windows on my node, and I dread reboots because I have to open them all manually after every one.

I'm just happy to have an opportunity to help you after you've gotten me out of so many jams getting my node up and running!

**Pull request merged**
